# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Build Dapper
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o homectl.linux_amd64 github.com/shauncampbell/homectl/cmd/homectl
        CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o homectl.darwin_amd64 github.com/shauncampbell/homectl/cmd/homectl
        CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o homectl.windows_amd64.exe github.com/shauncampbell/homectl/cmd/homectl
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 13
    - name: Add plugin for conventional commits
      run: npm install conventional-changelog-conventionalcommits
      working-directory: ./.github/workflows
    - name: Release to Github
      id: semantic
      working-directory: ./.github/workflows
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_AUTHOR_NAME: $GITHUB_ACTOR
        GITHUB_USER: $GITHUB_ACTOR
      run: npx semantic-release
